# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f08b0b32087e38a99adfd1bc24622963c989fcdbfd5330b2e545d3777355ed500d9c00107941ae9a09d6955fc96c9135025d6f5490dd735e557020ec38be15a7

test:
  secret_key_base: 8bc4c1c8d4167ba8b406601794b1b5806685dba64e2cd3642e382a8714d3f81c01f1fe42a1529f51bc7536a497b6738db395c98d5375618195a847293427defa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
